version: "3"
services:
  docker-inspect-api:
    build:
      context: .
      args: 
        - PLATFORM=lts
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - docker-inspect
    ports:
      - "8080:8080"
